# name 可以自定义
name: Deploy GitHub Alioss rentalsign

on:
  # 每当 push 到 main 分支时触发部署
  push:
    branches: 
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - run: yarn install --frozen-lockfile

      - name: Build VitePress site
        run: yarn docs:build
        
      - name: setup aliyun oss
        uses: manyuanrong/setup-ossutil@master
        with:
          endpoint: oss-cn-hangzhou.aliyuncs.com
          access-key-id: ${{secrets.SECRETS_ACCESS_KEY_ID}}
          access-key-secret: ${{secrets.SECRETS_ACCESS_KEY_SECRET}}
      - name: cp files to aliyun
        run: |
          ossutil rm oss://vuepressdocs/rentalsign/ -rf
          ossutil cp -rf docs/.vitepress/dist  oss://vuepressdocs/rentalsign/
